version: '3.1'

services:
  vue:
    image: vue
    build: ./client/
    ports:
      - 80:80

  backend:
    image: go
    build: .
    depends_on:
      - pg_db
      - vue
    ports:
      - 3000:3000

  pg_db:
    image: postgres
    restart: always
    container_name: postgresql
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=library
      - POSTGRES_DB=library
      - POSTGRES_USER=library
    volumes:
      - pg_db:/var/lib/postgresql/data
volumes:
  pg_db:
    driver: local