version: '3.1'

services:
  vue:
    image: vue
    build: ./client/
    ports:
      - 80:8080

  backend:
    image: go
    build: .
    depends_on:
      - db
      - vue
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    container_name: postgresql
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=library
      - POSTGRES_DB=library
      - POSTGRES_USER=library
  