version: '3.1'

services:
  vue:
    image: vue
    build: ./client/
    ports:
      - 8080:8080

  backend:
    image: go
    build: .
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    container_name: postgresql
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  